### ISSUE TITLE
Are themes gone?

### ISSUE THREAD

**Issue by 808dkaneohe** [rbjaxter/budhud#102]
i used the ToTH theme before but when i updated my hud, they were gone, y.

**Comment by rbjaxter** [comment]
I removed them from the base version of the HUD because they added a fair amount to the total filesize of the HUD. If you'd like to add your own background, I made a tutorial over here: https://github.com/rbjaxter/budhud/wiki/Custom-Menu-Background

If you'd like the original files, they should all be here: https://drive.google.com/file/d/0B2SDfbEASJaCcFcybHZQV0RaMHc/view?usp=sharing

**Comment by 808dkaneohe** [comment]
Thanks man, nice hud
