### ISSUE TITLE
Add 4Plug support

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#152]

**Comment by Evanito** [comment]
In order to do this you need to:
- Move the entire hud structure to the root folder. There is no technical reason to separate the .gitignore and the readme.md from the rest of the files, so this should not cause much of an issue.
EX: `rbjaxter/budhud/budhud/cfg/...` --> `rjbaxter/budhud/cfg/...`
- Create a `version.txt` with nothing other than raw text of a version number. You can start from one and increment it (can use decimals) every time you want to push an update. You will need to both increment the version in `data.txt` (below) and `version.txt` 
- Create a `data.txt` with information such as:
```
name=budhud
desc=A nifty little hud for TF2
creator=rbjaxter
url=https://github.com/rbjaxter/budhud
update_url=https://github.com/rbjaxter/budhud/archive/master.zip
version_url=https://raw.githubusercontent.com/rbjaxter/budhud/master/version.txt 
version=1.0
```
- You can create settings for certain parts of the hud that can be easily modified.
At the very least these settings support a fileswitcher for changing the `_Enabled` features. If you want to add some redundant files with some settings pre-changed that the user could switch between that could also work. Example config for another hud can be found [here](https://github.com/Sevin7/7HUD/blob/master/settings.data) for reference.

**Comment by rbjaxter** [comment]
Awesome, thanks for all of the info! I'll look into this down the road.

**Comment by rbjaxter** [comment]
Looking into this a bit more, 4plug may not be necessary given the structure of my hud. Customizations are pretty easy to implement right now, most of which require just moving a single file. I may still consider it down the road, though.

**Comment by Evanito** [comment]
I like the autoupdate feature of 4plug

**Comment by Evanito** [comment]
@rbjaxter I have some free time and would be willing to make a PR to add 4plug installation and customization support. Would you consider merging it?

**Comment by rbjaxter** [comment]
@Evanito terribly sorry for not getting back to you; I checked this when I had woken up and forgot to respond.

I'm still a bit hesitant about adding 4plug support, but I'll look into it again and re-consider it soon.
