### ISSUE TITLE
Only shows first digit on the timer for gate to close on Degroot Keep

### ISSUE THREAD

**Issue by Evanito** [rbjaxter/budhud#156]
Shows `2...` for the time left on the right of `C` cap point when it is in the 20-29 second range, for example. Shows single digits correctly.

**Comment by rbjaxter** [comment]
Huh, strange. I'll look into it now.

**Comment by rbjaxter** [comment]
Are you referring to this number?
https://dl.dropboxusercontent.com/u/12370275/ShareX/2017/01/hl2_2017-01-04_07-06-34.jpg

**Comment by rbjaxter** [comment]
Just expanded it out a bit (which also fixed its proximity to the CP, since the x/y pos values couldn't be adjusted. There shouldn't be any issues now. Thanks for spotting that!
![hl2_2017-01-04_07-07-53](https://cloud.githubusercontent.com/assets/509599/21646828/a7c69072-d24c-11e6-96ae-676d09af8118.jpg)
