### ISSUE TITLE
Budhud will not work 

### ISSUE THREAD

**Issue by Faceme765** [rbjaxter/budhud#252]
I don't know why budhud is not working, my problem seems to be kinda the same as issue #200. The difference is in this case i have the info.vdf file in the folder. 
![image](https://user-images.githubusercontent.com/43523450/45931966-613a8180-bf3b-11e8-95fd-92c5f6524cdf.png) In this case I don't get the loading screen that I'm supposed to get the hud also doesen't work in game either. I think My launch options are messing with it ,below is a screenshot of my launch options. 
![image](https://user-images.githubusercontent.com/43523450/45932012-f6d61100-bf3b-11e8-907d-8887c1b2ce2f.png) 
   I also tried it with no vpk's in my custom folder, Hope you can help!

**Comment by rbjaxter** [comment]
hey! 
so the screenshots help a ton here, thanks for including them. I believe it's because you have the hud folder `budhud-master` within another folder (in this case, also `budhud-master`. If you look at your hud's directory, it's `\custom\budhud-master\budhud-master`. This would be my guess on what's causing the issue. 

I'd try moving the `budhud-master` that has the files up one directory and then deleting the other `budhud-master` folder. If that doesn't work, let me know!

**Comment by rbjaxter** [comment]
Glad you got it figured out! :)
