### ISSUE TITLE
buttons on the top right on the menu do not show up on linux.

### ISSUE THREAD

**Issue by raenii** [rbjaxter/budhud#278]
title.
also, the alert button is missing.

**Comment by rbjaxter** [comment]
ah, I know what the issue is with the top right buttons; will post again when that's fixed.

as far as the alert button goes, it appears within the TV when you have a new alert; if it's not appearing there, try clicking on the tv to see if it opens up (TF2 alerts are sometimes glitchy and don't show the icon)

**Comment by raenii** [comment]
> ah, I know what the issue is with the top right buttons; will post again when that's fixed.
> 
> as far as the alert button goes, it appears within the TV when you have a new alert; if it's not appearing there, try clicking on the tv to see if it opens up (TF2 alerts are sometimes glitchy and don't show the icon)

sweet.
also, i thought the tv was the twitch stream thingy, so that's just me being dumb.
thanks!

**Comment by rbjaxter** [comment]
haha, nah that's not dumb at all; quite a few people have mentioned it. I may look at better ways to handle that in the future.

I just pushed a commit that might fix your issues; if you could download the hud and give it another go to see if it works, that'd be great :) https://github.com/rbjaxter/budhud/archive/master.zip

**Comment by rbjaxter** [comment]
Going to mark this as complete; let me know if you're still having issues!
