### ISSUE TITLE
[BUG] Disguise Health

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#327]
If I Disguise as Spy as some sort of class , the Health is not quite on the picture. I'm not sure if this is my fault, my resolution is 1920 x 1080 16:9  (Dont use Customize Health).
![image](https://user-images.githubusercontent.com/38357837/80925379-9487f800-8d8f-11ea-9f98-30679d9e7079.png)
Edit: Screenshot from whole Screen just when ya need it or whatever
![image](https://user-images.githubusercontent.com/38357837/80925981-72dd3f80-8d94-11ea-9073-7ffdbb12c9b0.png)

**Comment by rbjaxter** [comment]
I'll take a look, I believe it's due to all of the TargetID changes I made recently

**Comment by rbjaxter** [comment]
Will be fixed in the next commit 
![image](https://user-images.githubusercontent.com/509599/80927930-e6ac2780-8d55-11ea-9916-5acecc10134c.png)

**Comment by rbjaxter** [comment]
I may get rid of the team colored bar just because it makes the TargetID cross customization extra funky. I don't think there's really any way for me to fix the off-center issue when using the cross customization though, sadly: 
![image](https://user-images.githubusercontent.com/509599/80927972-3ee32980-8d56-11ea-87d9-cd7e3afd65b4.png)

**Comment by rbjaxter** [comment]
Fixed in https://github.com/rbjaxter/budhud/commit/eefa9ce

**Comment by RunawaySheld123** [comment]
Thats The Same Issue
