### ISSUE TITLE
[Improvement] Uber bar

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#329]
Hey it would be good, when the Vacinator indicator would be removed in the middle or displayed under the bar. You can't quite see how full it is between the ubers and it's displayed on the HP anyway. 
![image](https://user-images.githubusercontent.com/38357837/83164529-9c2b8a00-a10c-11ea-929e-869715d95c3e.png)

**Comment by rbjaxter** [comment]
The middle shield display updates current resistance selected while the one above the health does not, so it's still necessary to have it. Since I haven't heard anyone mention this prior, I may leave it as is and instead leave it as a customization option; it should be fairly straight-forward for people to remove in the `hudmediccharge` file.
