### ISSUE TITLE
[BUG] disguise counter

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#368]
The Medic's number is grey in the Red Team but white in the Blue Team as it should be. Tested in both Teams btw.

Red:
![image](https://user-images.githubusercontent.com/38357837/100471359-69257b80-30da-11eb-8679-3ecf3c9a18c6.png)
Blue:
![image](https://user-images.githubusercontent.com/38357837/100471369-6cb90280-30da-11eb-8cee-aebbe5fc12b7.png)

**Comment by rbjaxter** [comment]
this is shaping up to be quite a bizarre issue; I can't seem to isolate the issue. I thought this was an issue on my part (and it could still be). I copied the default `_tf2hud` variants of `medic_blue` and `medic_red` into their `_budhud` equivalents and had the same issues.

It appears that, for whatever reason, this specific label's color (in `\resource\ui\disguise_menu\medic.red`) is hard-coded. Interestingly, this only applies to those using the concise disguise menu.

Because `medic_blue` and `medic_red` are effectively the same files, simply swapping their contents should produce a solution, but it does not. So I'm _lead_ to believe this is actually a bizarre TF2 issue.

One over-the-top solution is to set `"Black"` in your colors file to be white instead, but this has unintended consequences (such as affecting some borders, for instance).

**Comment by rbjaxter** [comment]
Ah okay, so it is an issue with the default hud files interestingly enough; they have an `enabled` value incorrectly set: 
![image](https://user-images.githubusercontent.com/509599/100490230-ba2f7280-30ce-11eb-881e-4957753eb569.png)

I have fixed the value on my version of the hud, and will commit it soon.

**Comment by rbjaxter** [comment]
All fixed in the latest commits, thank you!
