### ISSUE TITLE
[BUG] Game mode popup 

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#384]
Idk if this is properly a bug, but on Joing a server and Create server the popup still remains there. Would be better if it disappears, Is away when you're ingame but is annoying. (Video aswell as Example. Its uploaded on Anonfiles because the file is to big for github)
https://anonfiles.com/P882w3sdu6/2021-04-21_23-14-06_mp4

**Comment by rbjaxter** [comment]
I don't actually believe there's anything I could do about that. At best there would be an animation that could be tied into when joining a server, but I don't think one of those exists. I'm lead to believe there isn't because I otherwise use default animations for most of those animations, so if a default animation did exist it would be using it.

If other huds don't have this issue though, it's definitely something I can look more into. For now, just clicking out of the window before joining a server is really the only solution I can think of.

**Comment by barbiehunter** [comment]
Okay, i will check out other HUDs when i have time, just have notice that and wanted to request it.

**Comment by barbiehunter** [comment]
Okay Update:
I checked now  Flawhud, Rayshud, Hypnotizehud and they dont had this Problem. I will check more when i have time.

**Comment by barbiehunter** [comment]
Ok i checked other HUDs and they have the same issue, Your choice if you want to check it still out our not.

**Comment by rbjaxter** [comment]
I checked available basehud animations + tested this on the default hud and it appears to happen with that as well, so I don't believe there's anything I can do about it unfortunately.
