### ISSUE TITLE
Rework powershell script to use `git pull` instead of downloading the zip.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [rbjaxter/budhud#404]
Downloading the master branch zip and extracting it is redundant, as `git pull` will automatically update all files to the current version.

Further more it is also recommended to use the `vpk.exe` tool included in TF2 itself, since it has potentially better compatibility with VPK files made for TF2.

**Comment by rbjaxter** [comment]
Since budhud is supported on TF2HUD.Editor (https://github.com/CriticalFlaw/TF2HUD.Editor), I'm not sure how concerned I am with updating the PS script for a while. I more so did it as more of a learning experience than anything else, but I am otherwise fairly unfamiliar with such scripting.

As far as the VPK tool goes, most huds do not play well being turned into VPKs because of custom fonts, unless the fonts are installed. I suppose I could probably look into adding a PS script for installing the fonts before packing the hud into a VPK, but it's not something I'm too worried about at the moment given that HUDs need to be fairly flexible for customizing.
