### ISSUE TITLE
[BUG] Killstreak Target info

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#414]
There seems to be a Bug with the name of people and the Killstreak. (Sorry for the Picture effect btw)
Target: 
![image](https://user-images.githubusercontent.com/38357837/134591570-7fcccd0f-a503-40ba-bc4b-369ccb140ec6.png)
How it should be:
![image](https://user-images.githubusercontent.com/38357837/134591626-7b369b2c-1d4d-4edc-8510-8486aa8e4a4c.png)

**Comment by rbjaxter** [comment]
hmm, this must be an issue with pinning the killstreak icon.

if you want to fix this on your end instead of waiting for a commit/having to update, I believe what I'll be doing is reverting the changes in this section to the old values on the left: <https://github.com/rbjaxter/budhud/commit/5559fbfb27beb170028a512f8b1be070a630c9f5#diff-71894bccd9eabde87a5ae507c5fef2a63453dc59aae6f7148171aaabb3787371L62-L71>

**Comment by barbiehunter** [comment]
Is this fixed now btw or not? dont find anything to it myself.

**Comment by rbjaxter** [comment]
I've been playing again and haven't noticed any issues with the current version of the hud. I'll have to keep a closer eye on it to see if I notice anything.
