### ISSUE TITLE
[BUG] Vote Popup Stays up

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#426]
Since the last TF2 update I notice that the votekick/map vote popup doesn't go away. As you can see in our picture it is also without text or something like that. Not sure if it's TF2 itself or you're HUD, to make sure i report it^^
![ywfEh6](https://user-images.githubusercontent.com/38357837/175044464-0eb74fb8-38fc-4f86-8d62-4a606cc77b98.png)
.

**Comment by rbjaxter** [comment]
Are you still having this issue? I haven't changed anything that might cause that, although checking it on a local server does show that it's...transparent now, for some reason 
![image](https://user-images.githubusercontent.com/509599/177017625-0d0836b8-4651-42af-8ddd-be5089895742.png)

**Comment by barbiehunter** [comment]
Haven't had the problem again yet, not sure if it's from TF2 itself or from the HUD (haven't tried another HUD yet). Had the problem on a community server (Delfy), if it matters.

**Comment by barbiehunter** [comment]
Have the last 2 days times looked at how it looks with the votes and have noticed a few things. Haven't tried it with any other HUD yet, but guess it's a bug after the vote panel was changed in general.

1. it can happen that the current vote with the old overlaps (so far only happend on community servers)
![image](https://user-images.githubusercontent.com/38357837/177311243-92059d62-ed75-4cdf-a6bc-94bf715527ae.png)

2. it probably does not apply to the default hud.
![image](https://user-images.githubusercontent.com/38357837/177311420-5138fe32-98ea-4610-bfe3-65aa1d1afcf6.png)

3. the vote panel becomes transparent only after a vote (for map votes on servers) 
https://user-images.githubusercontent.com/38357837/177311554-bbf04f45-1d68-4781-9757-c7130651399d.mp4

**Comment by rbjaxter** [comment]
I'm not sure what the deal with the transparent background is, it seems to have been introduced by one of the last few patches and there's nothing I can do about it, it seems.

As far as the overlapping votes, I'm not sure if that's a hud issue or not. If it's on custom servers, it may be something with how the plugin integrates into the TF2 vote UI that just hasn't been updated since the latest tf2 update. The only bug I can get to repro is the transparent background.
