### ISSUE TITLE
Skull icon in the weapon pick-up panel is very stretched

### ISSUE THREAD

**Issue by Kruphixx** [rbjaxter/budhud#471]
Resolution: 1920x1080

![Screenshot 2024-03-15 160843](https://github.com/rbjaxter/budhud/assets/50501742/c718f2e7-8032-4788-a12d-3df1e1c3570e)

**Comment by rbjaxter** [comment]
Yeah, unfortunately this is a tradeoff with having depleting health. I'm not personally aware of any way to mitigate this, since the VTF that shows the skull cannot be preloaded and thus removed in casual/comp. I'll poke around in the huds discord to check though, maybe this is what people use block fonts for or something (idk)
