### ISSUE TITLE
Casual mode map groups

### ISSUE THREAD

**Issue by ksh-b** [rbjaxter/budhud#535]
Currently its possible to save only one group of maps at a time.

Is it possible to have multiple such groups.

**Comment by rbjaxter** [comment]
Honestly I'm not too sure if that's possible or not. I don't know if there is a way to have multiple "map presets", as this would be a feature that has to be provided by the TF team. If you're familiar with another hud that has done this, let me know. But otherwise, I'm inclined to believe the functionality isn't possible atm
