### ISSUE TITLE
Shell script improvement suggestions

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#550]
- [budhud-compiler](https://github.com/rbjaxter/budhud-compiler) has a very cool option `--omitMissingDirectives`. It seems to speed up `hud_reloadscheme` a bit (on potato PCs). But on the other hand, this option breaks things if any HUD mods are installed outside of budhud (not sure if it's a common case). So, I would like to suggest asking a user before compiling if they want to enable this option or not (not sure about the default choice though).
- Recent updates to the shell script have added [the parent directory check](https://github.com/rbjaxter/budhud/blob/21634a7a75531eb4ed9e44071096c187114c94a8/budhud%20Updater.ps1#L131-L162). However, [4 of the 6 script functions](https://github.com/rbjaxter/budhud/blob/21634a7a75531eb4ed9e44071096c187114c94a8/budhud%20Updater.ps1#L944-L947) do not need this to work properly (if I understand it right). I don't know how many weirdos like me who keep all HUDs in one place and put either a symlink or in the case of budhud a compiled version in `custom`, but I'd really appreciate it if it could again be possible to compile the HUD with no need to run the script from `tf/custom/<budhud folder name>/`.

If you approve of any suggestions, I can potentially try to implement them (though I have barely any experience with powershell).

**Comment by rbjaxter** [comment]
For the first point, I'm a bit hesitant about it just because I have to imagine the compiler is already giving 99% of the performance benefits just from its initial pass of combining base directives. The only thing that flag would really be saving lines on are some "disabled by default" customization lines. I'm just not sure if the trade-off of the marginal performance gain outweighs the fact that they're stuck with whatever version of the hud they compiled (essentially). I suppose making it an option does allow someone to get the most pure-blooded non-#base-using-hud possible, but I just hope it wouldn't cause more confusion for those that use it.

For the parent directory check, I think i need to take a closer look myself at how that check compares to Check_HUDFiles and perhaps combine them. I may redo all the checks to avoid redunancy and also clean up them a bit more.

**Comment by rbjaxter** [comment]
@qkeitoe Let me know if this change to the check works for what you're doing. hopefully should, it just checks for folders it needs

**Comment by rbjaxter** [comment]
@qkeitoe That last commit adds a prompt for `--omitMissingDirectives` as well, I tested it on my end and had no issues but let me know if you run into anything 👍

**Comment by rbjaxter** [comment]
Agreed, I'll change that in a future commit
