### ISSUE TITLE
Potential customization ideas

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#561]
- hide static damage/heal numbers
- hide static class model (like `bh_player_hideclassmodel` but only for static image, like [this](https://github.com/qkeitoe/budhud/blob/23087c753cd759d555cf7126f8d9bbe28f5c1d8f/%23users/custom/resource/ui/hudplayerclass.res#L3))
- hide stats on loading screen
- show `ControlPointProgressBar`:
  ![image](https://github.com/user-attachments/assets/051edaeb-daf8-4478-95fb-ff525d999a88)

**Comment by rbjaxter** [comment]
Adding rocket's suggestion in the Discord to have a centered ammo customization (need to place it below uber % near cross)

**Comment by Sizzler48** [comment]
Similar to Hyponotize's HexHud, have the "game ready" screen just show players at the sides and still be able to see the game. The screen after the end of "competition begins in 30 seconds" Administrator voice line when casual matches are ready.

**Comment by rbjaxter** [comment]
I may look into it, though that element is actually the absolute worst element to work with since you need to effectively make a change -> find a game that is in pre-game -> see if the change worked -> repeat.

**Comment by rbjaxter** [comment]
Yeah, I imagine he removed the door visibility entirely and then animated the player lists to appear on the sides instead of in the middle. I don't know how valuable that would be to me personally, at least from an effort standpoint. But if someone wanted to spend the time implementing that as a customization option I suppose it'd be fine. I just don't want to steal anything from other huds

**Comment by rbjaxter** [comment]
1 - added
2 - added wouldn't be possible since it's controlled by a command as well and might confuse people not familiar with it (`cl_hud_playerclass_use_playermodel`)
3 - added
4 - added, though it does conflict with damage done/speedometer: 
![image](https://github.com/user-attachments/assets/43824c44-df9f-425d-97b8-1c55ef254c16)
5 (rocket) - added, and is compatible with dane's centered ammo or uber near crosshair. hopefully people are fine with it not being RIGHT next to the crosshair (since it'd otherwise be incompatible with the other two):
![image](https://github.com/user-attachments/assets/623ad2f8-ea9e-4574-8744-8dde8161f7c2)

**Comment by Sizzler48** [comment]
Add match status on HUD, giving player names around their class portrait.

![image](https://github.com/user-attachments/assets/4752af48-cbcf-4934-a5f3-e6a7806411df)

**Comment by rbjaxter** [comment]
> Add match status on HUD, giving player names around their class portrait.
> 
> ![image](https://private-user-images.githubusercontent.com/65160486/396095012-4752af48-cbcf-4934-a5f3-e6a7806411df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MjIzOTAsIm5iZiI6MTczNDgyMjA5MCwicGF0aCI6Ii82NTE2MDQ4Ni8zOTYwOTUwMTItNDc1MmFmNDgtY2JjZi00OTM0LWE1ZjMtZTZhNzgwNjQxMWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDIzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTE4YTQzNTNkMzg2OWY3N2JiMmQ4OWZlYWNlOWI0YzE0NDQwMjlkYzkzMGY3MzA2NDE0NjliOWE2OTcxYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N7ZcpxBRH2uKuW5MuW0zJI1cWZIXxuLbWrGI1duo3Hg)

![image](https://github.com/user-attachments/assets/2822036c-aa11-4d59-84ea-e8cfe32da3e8)
Probably the best it will be, I'll add it in a commit

**Comment by Sizzler48** [comment]
Holy crackers this looks awesome! Thank you so much!

**Comment by Sizzler48** [comment]
Is it possible to make the 6v6 match status customisation stretch to 12v12? To make it consistent with casual matches?

**Comment by Sizzler48** [comment]
Idea: remove healthcross from enemy deathcam target ID, since the player healthcross and targetID healthcross for teammates are optional.
