### ISSUE TITLE
Issues with `bh_tournamentpanels_*` customizations

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#567]
- Because of [the `#base` statements](https://github.com/rbjaxter/budhud/blob/5624ea4b77075c7ea0567cefae87b40b7a7e3e81/%23customization/bh_tournamentpanels_lower.res#L1) inside the customization files, those customizations don't work properly when put in the `#users/custom/#customization/_enabled/` folder. Although for those who customize budhud via `#users/custom/`, this is fairly easy to fix manually.
- Even when enabled in the normal way, most of the customizations don't seem to work properly. Also, based on the first screenshot from [here](https://imgur.com/a/Yup0DWb), I assume the player lists should be on the opposite sides by default, no?
  | default | allleft |
  | - | - |
  | <p align="center"> <img src="https://github.com/user-attachments/assets/51688a85-9703-4f5c-aea1-cfacf6fe24d9" /> </p> | <p align="center"> <img src="https://github.com/user-attachments/assets/d21c1cac-2c6c-4da2-932b-d7e03ede7445" /> </p> |

  | allright | lower |
  | - | - |
  | <p align="center"> <img src="https://github.com/user-attachments/assets/38973ddd-9147-4f95-837a-2b2028bfcc5c" /> </p> | <p align="center"> <img src="https://github.com/user-attachments/assets/7cfb968b-08d8-4594-b0e7-19e7923e17a6" /> </p> |

**Comment by rbjaxter** [comment]
I think I deleted the custom base file at some point and just never came back to it, leaving it broken. I think for now I'll just delete those customizations until someone mentions specifically wanting them (that's what I usually do for customizations, at least)

**Comment by rbjaxter** [comment]
I already removed them, so I wouldn't bother. I'll take another look to see if a lower customization is easy enough to implement, though.

**Comment by rbjaxter** [comment]
Just for some added context: The basic idea behind having each team on each side is that you're duplicating all of the information like so (courtesy of jarateking) and then just cutting off what you need:
![N0LWgOY](https://github.com/user-attachments/assets/48c5e8e9-394c-40e6-a72c-5d0a29a3076e)

The issue is that increasing `team1_player_base_offset_x` or `team2_player_base_offset_x` enough to have it "cutoff" with the right side of the screen results in aspect ratio dependent issues, and you can't just use an `r` value there so it'll position itself correctly regardless of resolution. It _seems_ that you can only use normal values here:
![image](https://github.com/user-attachments/assets/8fb98c01-a3c7-48b7-964a-e9ab5c816c4e)
